---
  - hosts: perf-server1
    become: true

    tasks:
      - include_vars: users.yml


      - name: add users
        user: 
          name: "{{ item.username }}"
          state: present
        with_items: '{{users}}'
      
      - name: Set authorized keys
        authorized_key:
          user: "{{ item.username }}"
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcJcNBh1P+jPkCWwIkt068hg6ZvuYnNaAUV7vqQbLHZqJgP5x0uHL18kr412ORY5E82WX/rNNCE8iJLCV4HvPA8wNeY2Hq0HyKzjyba4MjlBPaKWWK8N8FBCzF1tTKycQdPZTGmeFr3+1aizQdhWJ4G6YJl3yfLRpQqNUNzW9sbrhI8AfBjxhNnxOlFulawMBrZ9NRqzRAWfZppBn28uetV345hCXm08YgiUUu4ePLAHZNB5uMIDIS88BHy6FMwKK+IHAGTmAfNEjxlhl0kgwoVeKvVxMHIPVRMPR0waLCqn/6fXNlCeG51KjKTpOKHOPRdlWYhvahmuFIFE9B5NOB office
        with_items: '{{users}}'


  - hosts: perf-server2
    become: true

    tasks:
      - name: install JDK
        yum:
          name: java-1.7.0-openjdk
          state: absent
      - name: install JDK
        yum:
          name: java-1.8.0-openjdk
          state: present

      - name: install ruby
        yum:
          name: ruby
          state: present

      - name: install unzip
        yum:
          name: unzip
          state: present

      - name: install jmeter
        unarchive: 
          src: http://www-us.apache.org/dist//jmeter/binaries/apache-jmeter-4.0.zip
          dest: /
          remote_src: yes
      - name: add ssh sampler plugin
        get_url: 
          url: https://github.com/yciabaud/jmeter-ssh-sampler/releases/download/jmeter-ssh-sampler-1.1.1/ApacheJMeter_ssh-1.1.1.jar
          dest: /apache-jmeter-4.0/lib/ext/ApacheJMeter_ssh-1.1.1.jar
      
      - name: add ssh plugin
        get_url:
          url: https://github.com/yciabaud/jmeter-ssh-sampler/releases/download/jmeter-ssh-sampler-1.1.1/jsch-0.1.54.jar
          dest: /apache-jmeter-4.0/lib/ext/jsch-0.1.54.jar

      - name: generate load 1
        shell: dd if=/dev/zero of=/010000KB bs=10000K count=1

      - name: generate load 2
        shell: dd if=/dev/zero of=/001000KB bs=1000K count=1

      - name: generate load 3
        shell: dd if=/dev/zero of=/000100KB bs=100K count=1

      - name: load user files
        template:
            src: template/user.csv
            dest: /user.csv

      - name: load private key
        template:
            src: template/office.pem
            dest: /office.pem

      - name: change the permission
        file: 
          path: /office.pem
          state: file
          mode: 0400