---
  - hosts: perf-server2
    become: true

    tasks:
 #     - name: load test template
 #       template:
 #           src: template/test.j2
 #           dest: /test.jmx
 #       vars: 
 #         - threads: 200
 #     - name: test
 #       shell: /apache-jmeter-4.0/bin/jmeter -n -t /test.jmx -l /result.csv
 #     - name: load test template
 #       template:
 #           src: template/test.j2
 #           dest: /test.jmx
 




      - name: load test template
        template:
            src: template/sftp.j2
            dest: /sftp-10-010000KB.jmx
        vars: 
          thread_number: 10
          source_file: /010000KB

      - name: load test template
        template:
            src: template/sftp.j2
            dest: /sftp-50-001000KB.jmx
        vars: 
          thread_number: 50
          source_file: /0001000KB

      - name: load test template
        template:
            src: template/sftp.j2
            dest: /sftp-10-001000KB.jmx
        vars: 
          thread_number: 10
          source_file: /001000KB


      - name: load test template
        template:
            src: template/sftp.j2
            dest: /sftp-50-000100KB.jmx
        vars: 
          thread_number: 50
          source_file: /000100KB

      - name: load test template
        template:
            src: template/sftp.j2
            dest: /sftp-10-000100KB.jmx
        vars: 
          thread_number: 10
          source_file: /000100KB

      - name: test
        shell: /apache-jmeter-4.0/bin/jmeter -n -t /'{{ item }}'.jmx -l /'{{ item }}'.csv
        with_items:
          - sftp-10-010000KB
          - sftp-50-001000KB
          - sftp-10-001000KB
          - sftp-50-000100KB
          - sftp-10-000100KB

      - name: fetch the result csv
        fetch: 
          src: '{{ item }}'
          dest: result
        with_items:
          - /sftp-10-010000KB.jmx
          - /sftp-10-010000KB.csv
          - /sftp-50-001000KB.jmx
          - /sftp-50-001000KB.csv
          - /sftp-10-001000KB.jmx
          - /sftp-10-001000KB.csv
          - /sftp-50-000100KB.jmx
          - /sftp-50-000100KB.csv
          - /sftp-10-000100KB.jmx
          - /sftp-10-000100KB.csv

      - name: cleanup
        file:
          path: /result.csv
          state: absent



#      - name: load ruby summary
#        template:
#            src: template/summary.rb
#            dest: /summary.rb

#      - name: 
#        shell:  ruby /summary.rb
#        register: hello
#      - debug: msg="{{hello}}"
