---
  - hosts: perf-server1
    become: true

    tasks:
      - name: install httpd
        yum:
          name: httpd
          state: present
      - name: start httpd
        service:
          name: httpd
          state: started
          enabled: yes
      - name: load home page
        template:
            src: template/homepage.html
            dest: /var/www/html/homepage.html
      - name: install users
        user: 
          name: "{{ item }}"
          state: present
        loop:
          - tester1
          - tester2
  - hosts: perf-server2
    become: true

    tasks:
      - name: install JDK
        yum:
          name: java-1.7.0-openjdk
          state: absent
      - name: install JDK
        yum:
          name: java-1.8.0-openjdk
          state: present

      - name: install ruby
        yum:
          name: ruby
          state: present

      - name: install unzip
        yum:
          name: unzip
          state: present

      - name: install jmeter
        unarchive: 
          src: http://www-us.apache.org/dist//jmeter/binaries/apache-jmeter-4.0.zip
          dest: /
          remote_src: yes
      - name: add ssh sampler plugin
        get_url: 
          url: https://github.com/yciabaud/jmeter-ssh-sampler/releases/download/jmeter-ssh-sampler-1.1.1/ApacheJMeter_ssh-1.1.1.jar
          dest: /apache-jmeter-4.0/lib/ext/ApacheJMeter_ssh-1.1.1.jar
      
      - name: add ssh plugin
        get_url:
          url: https://github.com/yciabaud/jmeter-ssh-sampler/releases/download/jmeter-ssh-sampler-1.1.1/jsch-0.1.54.jar
          dest: /apache-jmeter-4.0/lib/ext/jsch-0.1.54.jar

