---
  - hosts: aws
    become: true

    tasks:
      - name: install docker
        yum:
          name: docker
          state: present
      - name: install pip docker-py
        pip: 
          name: docker-py
      - name: start docker
        service:
          name: docker
          state: started
          enabled: yes
      - name: start jenkins
        docker_container:
          name: 'jenkins'
          image: 'jenkins'
          ports:
              - '80:8080'
          restart_policy: 'always'
        when: jenkins|default(false) == true
      - name: start gitlab-ce
        docker_container:
          name: 'gitlab'
          image: 'gitlab/gitlab-ce'
          ports:
              - '80:80'
          restart_policy: 'always'
        when: gitlab|default(false) == true
      - name: start nexus
        docker_container:
          name: 'nexus'
          image: 'nexus'
          ports:
            - '80:8081'
          restart_policy: 'always'
        when: nexus|default(false) == true